// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jcooauychkkodfnylytk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impjb29hdXljaGtrb2RmbnlseXRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2MTEwNzIsImV4cCI6MjA1MDE4NzA3Mn0.feQvx9d69GfgrY45DQy2oDbde7JUStF7kvxwcXV8pIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);